
# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0CA-dbH4H2P7ezl1cB52GwXdannGJjt
"""

# Descargamos librerías necesarías para todo el proceso
import requests
import sys

#Verificamos conexión con la página web
def verificar_conexion(url):
    """
    Intenta conectar con la URL especificada y verifica el código de estado HTTP.

    Args:
        url (str): La URL de la página web objetivo.

    Returns:
        bool: True si la conexión fue exitosa (código 200), False en caso contrario.
    """
    # Usamos un User-Agent para simular un navegador real.
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    print(f"Intentando conectar con: {url}")
    print("--------------------------------------------------")

    try:
        # Realizamos la petición HTTP GET con un tiempo de espera de 10 segundos
        response = requests.get(url, headers=headers, timeout=10)

        codigo_estado = response.status_code
        print(f"Conexión establecida. Código de estado HTTP: {codigo_estado}")

        if codigo_estado == 200:
            print("¡La conexión fue exitosa! El servidor respondió correctamente.")
            return True
        elif codigo_estado >= 400 and codigo_estado < 500:
            print(f"Error del Cliente ({codigo_estado}). Es posible que la página no exista (404) o que el servidor haya bloqueado la solicitud (403).")
            return False
        elif codigo_estado >= 500:
            print(f"Error del Servidor ({codigo_estado}). El sitio web tiene problemas internos.")
            return False
        else:
            print(f"Código de estado no esperado ({codigo_estado}).")
            return False


    except requests.exceptions.ConnectionError as e:
        print(f"ERROR CRÍTICO DE CONEXIÓN:")
        print(" Asegúrate de que la URL esté escrita correctamente (incluyendo http:// o https://).")
        print(f"    Detalles: {e}")
        return False
    except requests.exceptions.Timeout:
        print(f"ERROR: Tiempo de Espera (Timeout) agotado. El servidor tardó demasiado en responder.")
        return False
    except Exception as e:
        print(f"Ocurrió un error inesperado: {e}")
        return False

# --- Bloque Principal de Ejecución ---
if __name__ == "__main__":
    url_objetivo = "https://sgonorte.bomberosperu.gob.pe/24horas"

    print(f"--- INICIO DE PRUEBA DE CONEXIÓN ---")

    if verificar_conexion(url_objetivo):
        print("\n¡Podemos proceder con la extracción de datos!")
    else:
        print("\nLa conexión falló. No es posible extraer datos en este momento.")

    print("--- FIN DE PRUEBA DE CONEXIÓN ---")

# URL base para los detalles de cada incidente, usando el "numparte"
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
from concurrent.futures import ThreadPoolExecutor

# INSTALACIÓN: Si es una sesión nueva de Colab, ejecuta esto primero:
# !pip install requests beautifulsoup4 pandas

# URL base para los detalles de cada incidente, usando el "numparte"
BASE_DETAIL_URL = "https://sgonorte.bomberosperu.gob.pe/24horas/Home/Map?numparte="

def extraer_coordenadas_y_direccion(id_emergencia):
    """
    Intenta extraer la dirección y coordenadas de la página de detalle.
    Utiliza búsqueda por estructura HTML y, como alternativa, por patrón de texto (RegEx).
    """
    url_detalle = BASE_DETAIL_URL + id_emergencia
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    # Mensajes por defecto si no se encuentra la información
    direccion_defecto = "Contenido NO Cargado (JS Requerido)"
    coordenadas_defecto = "N/A"

    try:
        response = requests.get(url_detalle, headers=headers, timeout=10)
        response.raise_for_status()

        # ----------------------------------------------------
        # 1. Intento A: Búsqueda basada en la estructura HTML (más precisa)
        # ----------------------------------------------------
        soup_detalle = BeautifulSoup(response.content, 'html.parser')

        # Buscamos el último <td> con colspan="2", donde está la dirección
        celdas_colspan_2 = soup_detalle.find_all('td', colspan='2')

        if celdas_colspan_2:
            # Seleccionamos el último, que es donde encontraste la dirección
            direccion_celda = celdas_colspan_2[-1]
            texto_completo = direccion_celda.get_text().strip()

            # Limpiar espacios múltiples
            texto_limpio = re.sub(r'\s{2,}', ' ', texto_completo)

            # Patrón para extraer las coordenadas: (-XX.XXXX,-YY.YYYY)
            match_coords = re.search(r'\(([-]?\d+\.\d+),([-]?\d+\.\d+)\)', texto_limpio)

            if match_coords:
                latitud = match_coords.group(1)
                longitud = match_coords.group(2)
                coordenadas = f"{latitud}, {longitud}"

                # Eliminar las coordenadas del texto para dejar solo la dirección limpia
                direccion_limpia = re.sub(r'\s*\(([-]?\d+\.\d+),([-]?\d+\.\d+)\)\s*', ' ', texto_limpio).strip()

                return direccion_limpia, coordenadas
            else:
                # Si el <td> existe pero no tiene el formato de coordenadas, devolvemos el texto encontrado
                return texto_limpio, coordenadas_defecto

        # ----------------------------------------------------
        # 2. Intento B: Búsqueda agresiva de Coordenadas en el texto fuente (Fallback)
        # ----------------------------------------------------

        # Busca el patrón de coordenadas en el texto sin procesar (podría estar en JS oculto)
        match_script_coords = re.search(r'([-]?\d+\.\d+), ?([-]?\d+\.\d+)', response.text)

        if match_script_coords:
            latitud = match_script_coords.group(1)
            longitud = match_script_coords.group(2)
            coordenadas = f"{latitud}, {longitud}"

            # Si se encuentra en el script, la dirección detallada no será visible para 'requests'
            return direccion_defecto, coordenadas

        # Si no se encontró nada en ambos intentos
        return direccion_defecto, coordenadas_defecto

    except requests.exceptions.HTTPError as err:
        # Manejar errores de HTTP (404, 500, etc.)
        return f"Error HTTP ({err.response.status_code})", coordenadas_defecto
    except Exception as e:
        # Manejar otros errores de conexión o parsing
        return f"Error al Conectar/Extraer Detalle: {type(e).__name__}", coordenadas_defecto


def extraer_tabla_emergencias(url):
    """
    Paso 1: Extrae los datos iniciales (ID, Fecha, Tipo) de la tabla principal.
    CORRECCIÓN: La búsqueda de la tabla es más flexible para evitar el error anterior.
    """
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    try:
        response = requests.get(url, headers=headers, timeout=15)
        response.raise_for_status()
    except Exception as e:
        print(f"[❌] ERROR al obtener la página principal: {e}")
        return None

    soup = BeautifulSoup(response.content, 'html.parser')

    # *** CORRECCIÓN CRÍTICA AQUÍ ***
    # Buscamos una tabla que contenga "table-bordered" en su clase (más flexible)
    tabla = soup.find('table', class_=lambda c: c and 'table-bordered' in c.split())

    if not tabla:
        print("[❌] ERROR: No se encontró la tabla de emergencias. (La clase podría haber cambiado)")
        return None

    datos_iniciales = []
    # Busca todas las filas de la tabla principal, excluyendo el encabezado <thead>
    filas = tabla.find('tbody').find_all('tr')

    for fila in filas:
        celdas = fila.find_all(['th', 'td'])

        # Debe tener al menos 5 celdas con datos relevantes (Nro Parte, Fecha/Hora, Tipo)
        if len(celdas) >= 5:
            datos_fila = {}

            # Columna 1: Nro Parte -> ID único (celda[1])
            nro_parte_element = celdas[1].find('span')
            datos_fila['ID Mapa (Nro Parte)'] = nro_parte_element.get_text().strip() if nro_parte_element else "N/A"

            # Columna 2: Fecha y hora (celda[2])
            fecha_hora_element = celdas[2].find('span')
            datos_fila['Fecha y hora'] = fecha_hora_element.get_text().strip() if fecha_hora_element else "N/A"

            # Columna 4: Tipo (celda[4])
            tipo_element = celdas[4].find('span')
            tipo = tipo_element.get_text().strip() if tipo_element else celdas[4].get_text().strip()
            datos_fila['Tipo'] = re.sub(r'\s{2,}', ' ', tipo).strip() # Limpiamos espacios

            datos_iniciales.append(datos_fila)

    return pd.DataFrame(datos_iniciales)


# --- Bloque Principal de Ejecución ---
if __name__ == "__main__":
    url_objetivo = "https://sgonorte.bomberosperu.gob.pe/24horas"

    print("--- INICIO DE EXTRACCIÓN DE DATOS ---")

    df_base = extraer_tabla_emergencias(url_objetivo)

    if df_base is not None and not df_base.empty:
        print(f"[+] Se extrajeron {len(df_base)} registros base.")
        print("[*] Iniciando la búsqueda de detalles geográficos (navegación a sub-páginas en paralelo)...")

        direcciones_y_coords = []

        # Usamos ThreadPoolExecutor para hacer las solicitudes de detalle en paralelo (más rápido)
        with ThreadPoolExecutor(max_workers=10) as executor:
            # Mapeamos la función de extracción de detalles a la columna de IDs
            future_to_id = executor.map(extraer_coordenadas_y_direccion, df_base['ID Mapa (Nro Parte)'])

            # Recogemos los resultados
            for result in future_to_id:
                direcciones_y_coords.append(result)

        # Separamos los resultados en un DataFrame de detalles
        df_detalle = pd.DataFrame(direcciones_y_coords, columns=['Dirección Completa', 'Coordenadas (Lat, Lon)'])

        # Combinar el DataFrame base con los detalles
        df_final = pd.concat([df_base.reset_index(drop=True), df_detalle], axis=1)

        print("\n" + "="*70)
        print("✅ EXTRACCIÓN EXITOSA. DATAFRAME COMPLETO GENERADO.")
        print("="*70)

        # Mostramos las primeras 5 filas del DataFrame final
        print("Primeras 5 filas del DataFrame:")
        print(df_final.head(5))

        print(f"\n[INFO] Total de registros procesados: {len(df_final)}")
    elif df_base is not None and df_base.empty:
        print("\n[INFO] La página cargó, pero no se encontraron registros de emergencias.")
    else:
        print("\nProceso de extracción fallido en el paso inicial.")

    print("\n--- FIN DEL PROCESO ---")

# Filtramos solo los accidentes de tránsito

def filtrar_accidentes_de_transito(df):
    """
    Filtra el DataFrame para incluir solo incidentes relacionados con vehículos de tránsito.

    Busca las palabras 'AUTOMOVIL', 'CAMIONETA', 'MOTO', 'VEHICULAR'
    en la columna 'Tipo' de forma insensible a mayúsculas/minúsculas.
    """

    # 1. Definir los patrones de búsqueda (los juntamos con | que significa 'OR' en RegEx)
    patrones_vehiculos = 'AUTOMOVIL|CAMIONETA|MOTO|VEHICULAR'

    # 2. Aplicar el filtro a la columna 'Tipo'
    # .str.contains() busca el patrón
    # case=False hace que la búsqueda no distinga entre mayúsculas y minúsculas
    # na=False asegura que las filas vacías no se incluyan
    df_filtrado = df[
        df['Tipo'].str.contains(patrones_vehiculos, case=False, na=False)
    ].copy() # Usamos .copy() para evitar advertencias de Pandas

    return df_filtrado

# ----------------------------------------------------
# 1. Ejecutar la función de filtrado
# ----------------------------------------------------
# Creamos un nuevo DataFrame llamado df_transito
df_transito = filtrar_accidentes_de_transito(df_final)

# ----------------------------------------------------
# 2. Mostrar los resultados
# ----------------------------------------------------
print("="*60)
print(f"TABLA DE ACCIDENTES DE TRÁNSITO ENCONTRADOS ({len(df_transito)} registros)")
print("="*60)

# Mostramos el DataFrame filtrado
if not df_transito.empty:
    # Mostramos las columnas más relevantes
    print(df_transito[['Fecha y hora', 'Tipo', 'Dirección Completa', 'Coordenadas (Lat, Lon)']])
else:
    print("No se encontraron registros de accidentes de tránsito con los patrones definidos.")

# Información sobre el resultado
print(f"\n[INFO] Número total de accidentes de tránsito encontrados: {len(df_transito)}")
